### ISSUE TITLE
UI improvements to the extension configuration page 

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/plesk-extension#36]
We should change the current error message to be more user friendly:

![screenshot from 2017-05-05 11-04-49](https://cloud.githubusercontent.com/assets/1538458/25737897/d5ae59b2-3182-11e7-98f9-0898b82464ae.png)

This should:

 1. Not be an "error" but likely warning or info
 2. Be more informative

--------------------

The descriptive text should also be removed from:
 - AntiSpam API URL 
 - SpamFilter API hostname 
 - SpamFilter API username 
 - SpamFilter API password 
 - Primary MX *
 - Secondary MX 
 - Tertiary MX 
 - Support email

**Comment by mihaipetrea** [comment]
Hi there,
Please find attached the UI design for this screen. As far as I understood, the icon that we've used in this message its not present on the list of UI elements that you use across the website. I'm ok by changing it, but in order to do this, we will need access to a list of available icons. Thanks!

![36---change-error-message-when-no-configuration-is-present](https://user-images.githubusercontent.com/25821365/27676360-4216d22e-5cb6-11e7-85bf-eb772e9891d3.png)

**Comment by lorentina** [comment]
Change automated tests in https://github.com/SpamExperts/plesk-extension/commit/af4476587cd25ef5d704238b38f02604813cdaf0

**Comment by for93t** [comment]
@lorentina, what's the status here?

**Comment by lorentina** [comment]
Verified. Waiting for pull-request #40

**Comment by alexkiro** [comment]
This needs to stay open until it's:

 1. Re-verified
 2. Published in Plesk store.

**Comment by Agoodfella** [comment]
Re-checked the changes made here.

Verified.

**Comment by alexkiro** [comment]
New version published.
